spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: y385755490
    password: 5201314402
    url: jdbc:mysql://192.168.43.136/SpringCloud_Sell
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
