spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: y385755490
    password: 5201314402
    url: jdbc:mysql://192.168.43.135/SpringCloud_Sell
    jpa:
      show-sql: true
euraka:
  client:
    service-url:
      defaultZone: http://localhost:8761/euraka/
